package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;




/**
 * Almacen generated by hbm2java
 */
@Component
public class Almacen  implements java.io.Serializable {


     private long idalmacen;
     private String nombre;
     private String direccion;
     private String estado;
     private Set<AlmacenProducto> almacenProductos = new HashSet<AlmacenProducto>(0);

    public Almacen() {
    }

    public Almacen(long idalmacen, String nombre, String direccion) {
       this.idalmacen = idalmacen;
       this.nombre = nombre;
       this.direccion = direccion;
    }
   
    public long getIdalmacen() {
        return this.idalmacen;
    }
    
    public void setIdalmacen(long idalmacen) {
        this.idalmacen = idalmacen;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Set<AlmacenProducto> getAlmacenProductos() {
        return almacenProductos;
    }

    public void setAlmacenProductos(Set<AlmacenProducto> almacenProductos) {
        this.almacenProductos = almacenProductos;
    }




}


