package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * AlmacenProducto generated by hbm2java
 */
@Component
public class AlmacenProducto  implements java.io.Serializable {


     private long idalmacenproducto;

    public AlmacenProducto() {
    }

    public AlmacenProducto(long idalmacenproducto) {
       this.idalmacenproducto = idalmacenproducto;
    }
   
    public long getIdalmacenproducto() {
        return this.idalmacenproducto;
    }
    
    public void setIdalmacenproducto(long idalmacenproducto) {
        this.idalmacenproducto = idalmacenproducto;
    }




}


