package org.siga.be;
// Generated 09/06/2017 11:14:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Categoria generated by hbm2java
 */
@Component
public class Categoria  implements java.io.Serializable {


     private int idcategoria;
     private String descripcion;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Categoria() {
    }

	
    public Categoria(int idcategoria, String descripcion) {
        this.idcategoria = idcategoria;
        this.descripcion = descripcion;
    }
    public Categoria(int idcategoria, String descripcion, Set<Producto> productos) {
       this.idcategoria = idcategoria;
       this.descripcion = descripcion;
       this.productos = productos;
    }
   
    public int getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(int idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


