package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Clase generated by hbm2java
 */
@Component
public class Clase  implements java.io.Serializable {


     private long idclase;
     private Familia familia;
     private String descripcion;
     private String estado;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Clase() {
    }

	
    public Clase(long idclase, String descripcion, String estado) {
        this.idclase = idclase;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public Clase(long idclase, Familia familia, String descripcion, String estado, Set<Producto> productos) {
       this.idclase = idclase;
       this.familia = familia;
       this.descripcion = descripcion;
       this.estado = estado;
       this.productos = productos;
    }
   
    public long getIdclase() {
        return this.idclase;
    }
    
    public void setIdclase(long idclase) {
        this.idclase = idclase;
    }
    public Familia getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(Familia familia) {
        this.familia = familia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


