package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * Dependencia generated by hbm2java
 */
@Component
public class Dependencia  implements java.io.Serializable {


     private long iddependencia;
     private String descripcion;
     private String estado;

    public Dependencia() {
    }

    public Dependencia(long iddependencia, String descripcion, String estado) {
       this.iddependencia = iddependencia;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public long getIddependencia() {
        return this.iddependencia;
    }
    
    public void setIddependencia(long iddependencia) {
        this.iddependencia = iddependencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


