package org.siga.be;
// Generated 18/12/2017 12:00:52 PM by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * Equivalencia generated by hbm2java
 */
@Component
public class Equivalencia  implements java.io.Serializable {


     private int idequivalencia;
     private UnidadMedida unidadMedida;
     private String interpretacion;
     private double factor;
     private boolean estado;
     private UnidadMedida unidadEquivalente;

    public Equivalencia() {
        this.idequivalencia = 0;
        unidadMedida = new UnidadMedida();
        unidadEquivalente = new UnidadMedida();
    }

    public Equivalencia(int idequivalencia, UnidadMedida unidadMedida, String interpretacion, double factor, boolean estado) {
       this.idequivalencia = idequivalencia;
       this.unidadMedida = unidadMedida;
       this.interpretacion = interpretacion;
       this.factor = factor;
       this.estado = estado;
    }
   
    public int getIdequivalencia() {
        return this.idequivalencia;
    }
    
    public void setIdequivalencia(int idequivalencia) {
        this.idequivalencia = idequivalencia;
    }
    public UnidadMedida getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(UnidadMedida unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public String getInterpretacion() {
        return this.interpretacion;
    }
    
    public void setInterpretacion(String interpretacion) {
        this.interpretacion = interpretacion;
    }
    public double getFactor() {
        return this.factor;
    }
    
    public void setFactor(double factor) {
        this.factor = factor;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public UnidadMedida getUnidadEquivalente() {
        return unidadEquivalente;
    }

    public void setUnidadEquivalente(UnidadMedida unidadEquivalente) {
        this.unidadEquivalente = unidadEquivalente;
    }

}


