package org.siga.be;
// Generated 08/03/2018 11:27:36 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * Kardex generated by hbm2java
 */
@Component
public class Kardex  implements java.io.Serializable {


     private int idkardex;
     private Almacen almacen;
     private Producto producto;
     private Date fechaMov;
     private String movimiento;
     private String detalle;
     private double cantidad;
     private BigDecimal valorUnit;
     private String horaMov;
     private long numero;
     private long nroOrden;
     private long idAlamcenproducto;
     private String comprobante;
     private String nroComprobante;

    public Kardex() {
    }

	
    public Kardex(int idkardex, Producto producto, Date fechaMov, String movimiento, double cantidad, BigDecimal valorUnit, long numero) {
        this.idkardex = idkardex;
        this.producto = producto;
        this.fechaMov = fechaMov;
        this.movimiento = movimiento;
        this.cantidad = cantidad;
        this.valorUnit = valorUnit;
        this.numero = numero;
    }
   
    public int getIdkardex() {
        return this.idkardex;
    }
    
    public void setIdkardex(int idkardex) {
        this.idkardex = idkardex;
    }
    
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getFechaMov() {
        return this.fechaMov;
    }
    
    public void setFechaMov(Date fechaMov) {
        this.fechaMov = fechaMov;
    }
    public String getMovimiento() {
        return this.movimiento;
    }
    
    public void setMovimiento(String movimiento) {
        this.movimiento = movimiento;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getValorUnit() {
        return this.valorUnit;
    }
    
    public void setValorUnit(BigDecimal valorUnit) {
        this.valorUnit = valorUnit;
    }
   
    public String getHoraMov() {
        return this.horaMov;
    }
    
    public void setHoraMov(String horaMov) {
        this.horaMov = horaMov;
    }
    
    public long getNumero() {
        return this.numero;
    }
    
    public void setNumero(long numero) {
        this.numero = numero;
    }
    public long getNroOrden() {
        return this.nroOrden;
    }
    
    public void setNroOrden(long nroOrden) {
        this.nroOrden = nroOrden;
    }

    public Almacen getAlmacen() {
        return almacen;
    }

    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }

    public long getIdAlamcenproducto() {
        return idAlamcenproducto;
    }

    public void setIdAlamcenproducto(long idAlamcenproducto) {
        this.idAlamcenproducto = idAlamcenproducto;
    }

    public String getComprobante() {
        return comprobante;
    }

    public void setComprobante(String comprobante) {
        this.comprobante = comprobante;
    }

    public String getNroComprobante() {
        return nroComprobante;
    }

    public void setNroComprobante(String nroComprobante) {
        this.nroComprobante = nroComprobante;
    }




}


