package org.siga.be;
// Generated 09/06/2017 11:14:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Marca generated by hbm2java
 */
@Component
public class Marca  implements java.io.Serializable {


     private int idmarca;
     private String descripcion;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Marca() {
    }

	
    public Marca(int idmarca, String descripcion) {
        this.idmarca = idmarca;
        this.descripcion = descripcion;
    }
    public Marca(int idmarca, String descripcion, Set<Producto> productos) {
       this.idmarca = idmarca;
       this.descripcion = descripcion;
       this.productos = productos;
    }
   
    public int getIdmarca() {
        return this.idmarca;
    }
    
    public void setIdmarca(int idmarca) {
        this.idmarca = idmarca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


