package org.siga.be;
// Generated 08/09/2018 09:49:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Menu generated by hbm2java
 */
@Component
public class Menu  implements java.io.Serializable {


     private long idmenu;
     private Menu menu;
     private Rol rol;
     private String nombre;
     private String tipo;
     private int estado;
     private String url;
     private Set<Menu> menus = new HashSet<Menu>(0);

    public Menu() {
    }

	
    public Menu(long idmenu, Rol rol, String nombre, String tipo, int estado) {
        this.idmenu = idmenu;
        this.rol = rol;
        this.nombre = nombre;
        this.tipo = tipo;
        this.estado = estado;
    }
    public Menu(long idmenu, Menu menu, Rol rol, String nombre, String tipo, int estado, Set<Menu> menus) {
       this.idmenu = idmenu;
       this.menu = menu;
       this.rol = rol;
       this.nombre = nombre;
       this.tipo = tipo;
       this.estado = estado;
       this.menus = menus;
    }
   
    public long getIdmenu() {
        return this.idmenu;
    }
    
    public void setIdmenu(long idmenu) {
        this.idmenu = idmenu;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set<Menu> getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set<Menu> menus) {
        this.menus = menus;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }




}


