package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * NotaSalidaDetalle generated by hbm2java
 */
@Component
public class NotaSalidaDetalle  implements java.io.Serializable {


     private long idnotasalidadetalle;
     private int idProducto;
     private Integer idUnidadmedida;
     private int idNotasalida;
     private int cantidad;

    public NotaSalidaDetalle() {
    }

	
    public NotaSalidaDetalle(long idnotasalidadetalle, int idProducto, int idNotasalida, int cantidad) {
        this.idnotasalidadetalle = idnotasalidadetalle;
        this.idProducto = idProducto;
        this.idNotasalida = idNotasalida;
        this.cantidad = cantidad;
    }
    public NotaSalidaDetalle(long idnotasalidadetalle, int idProducto, Integer idUnidadmedida, int idNotasalida, int cantidad) {
       this.idnotasalidadetalle = idnotasalidadetalle;
       this.idProducto = idProducto;
       this.idUnidadmedida = idUnidadmedida;
       this.idNotasalida = idNotasalida;
       this.cantidad = cantidad;
    }
   
    public long getIdnotasalidadetalle() {
        return this.idnotasalidadetalle;
    }
    
    public void setIdnotasalidadetalle(long idnotasalidadetalle) {
        this.idnotasalidadetalle = idnotasalidadetalle;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public Integer getIdUnidadmedida() {
        return this.idUnidadmedida;
    }
    
    public void setIdUnidadmedida(Integer idUnidadmedida) {
        this.idUnidadmedida = idUnidadmedida;
    }
    public int getIdNotasalida() {
        return this.idNotasalida;
    }
    
    public void setIdNotasalida(int idNotasalida) {
        this.idNotasalida = idNotasalida;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


