package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * NotaSalida generated by hbm2java
 */
@Component
public class NotaSalida  implements java.io.Serializable {


     private long idnotasalida;
     private int numero;
     private Date fechaReg;
     private Integer idTiposalida;
     private Integer idPedido;
     private int idUserReg;
     private Integer idTipomovimiento;
     private int idAlmacenOrigen;
     private Integer idAlmacenDestino;
     private int idCentrogasto;
     private String observacion;
     private Integer idComprobante;

    public NotaSalida() {
    }

	
    public NotaSalida(long idnotasalida, int numero, int idUserReg, int idAlmacenOrigen, int idCentrogasto, String observacion) {
        this.idnotasalida = idnotasalida;
        this.numero = numero;
        this.idUserReg = idUserReg;
        this.idAlmacenOrigen = idAlmacenOrigen;
        this.idCentrogasto = idCentrogasto;
        this.observacion = observacion;
    }
    public NotaSalida(long idnotasalida, int numero, Date fechaReg, Integer idTiposalida, Integer idPedido, int idUserReg, Integer idTipomovimiento, int idAlmacenOrigen, Integer idAlmacenDestino, int idCentrogasto, String observacion, Integer idComprobante) {
       this.idnotasalida = idnotasalida;
       this.numero = numero;
       this.fechaReg = fechaReg;
       this.idTiposalida = idTiposalida;
       this.idPedido = idPedido;
       this.idUserReg = idUserReg;
       this.idTipomovimiento = idTipomovimiento;
       this.idAlmacenOrigen = idAlmacenOrigen;
       this.idAlmacenDestino = idAlmacenDestino;
       this.idCentrogasto = idCentrogasto;
       this.observacion = observacion;
       this.idComprobante = idComprobante;
    }
   
    public long getIdnotasalida() {
        return this.idnotasalida;
    }
    
    public void setIdnotasalida(long idnotasalida) {
        this.idnotasalida = idnotasalida;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Integer getIdTiposalida() {
        return this.idTiposalida;
    }
    
    public void setIdTiposalida(Integer idTiposalida) {
        this.idTiposalida = idTiposalida;
    }
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public int getIdUserReg() {
        return this.idUserReg;
    }
    
    public void setIdUserReg(int idUserReg) {
        this.idUserReg = idUserReg;
    }
    public Integer getIdTipomovimiento() {
        return this.idTipomovimiento;
    }
    
    public void setIdTipomovimiento(Integer idTipomovimiento) {
        this.idTipomovimiento = idTipomovimiento;
    }
    public int getIdAlmacenOrigen() {
        return this.idAlmacenOrigen;
    }
    
    public void setIdAlmacenOrigen(int idAlmacenOrigen) {
        this.idAlmacenOrigen = idAlmacenOrigen;
    }
    public Integer getIdAlmacenDestino() {
        return this.idAlmacenDestino;
    }
    
    public void setIdAlmacenDestino(Integer idAlmacenDestino) {
        this.idAlmacenDestino = idAlmacenDestino;
    }
    public int getIdCentrogasto() {
        return this.idCentrogasto;
    }
    
    public void setIdCentrogasto(int idCentrogasto) {
        this.idCentrogasto = idCentrogasto;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdComprobante() {
        return this.idComprobante;
    }
    
    public void setIdComprobante(Integer idComprobante) {
        this.idComprobante = idComprobante;
    }




}


