package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * NotaEntrada generated by hbm2java
 */
@Component
public class NotaEntrada  implements java.io.Serializable {


     private int idnotaentrada;
     private OrdenCompra ordenCompra;
     private Proveedor proveedor;
     private TipoMovimiento tipoMovimiento;
     private long numero;
     private Date fechaReg;
     private int idTipoentrada;
     private Date fechaDocref;
     private String nroDocref;
     private int idAlmacendestino;
     private int idUserReg;
     private String observacion;
     private Integer idComprobante;
     private Set<NotaEntradaDetalle> notaEntradaDetalles = new HashSet<NotaEntradaDetalle>(0);

    public NotaEntrada() {
    }

	
    public NotaEntrada(int idnotaentrada, long numero, Date fechaReg, int idTipoentrada, int idAlmacendestino, int idUserReg, String observacion) {
        this.idnotaentrada = idnotaentrada;
        this.numero = numero;
        this.fechaReg = fechaReg;
        this.idTipoentrada = idTipoentrada;
        this.idAlmacendestino = idAlmacendestino;
        this.idUserReg = idUserReg;
        this.observacion = observacion;
    }
    public NotaEntrada(int idnotaentrada, OrdenCompra ordenCompra, Proveedor proveedor, TipoMovimiento tipoMovimiento, long numero, Date fechaReg, int idTipoentrada, Date fechaDocref, String nroDocref, int idAlmacendestino, int idUserReg, String observacion, Integer idComprobante, Set<NotaEntradaDetalle> notaEntradaDetalles) {
       this.idnotaentrada = idnotaentrada;
       this.ordenCompra = ordenCompra;
       this.proveedor = proveedor;
       this.tipoMovimiento = tipoMovimiento;
       this.numero = numero;
       this.fechaReg = fechaReg;
       this.idTipoentrada = idTipoentrada;
       this.fechaDocref = fechaDocref;
       this.nroDocref = nroDocref;
       this.idAlmacendestino = idAlmacendestino;
       this.idUserReg = idUserReg;
       this.observacion = observacion;
       this.idComprobante = idComprobante;
       this.notaEntradaDetalles = notaEntradaDetalles;
    }
   
    public int getIdnotaentrada() {
        return this.idnotaentrada;
    }
    
    public void setIdnotaentrada(int idnotaentrada) {
        this.idnotaentrada = idnotaentrada;
    }
    public OrdenCompra getOrdenCompra() {
        return this.ordenCompra;
    }
    
    public void setOrdenCompra(OrdenCompra ordenCompra) {
        this.ordenCompra = ordenCompra;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public TipoMovimiento getTipoMovimiento() {
        return this.tipoMovimiento;
    }
    
    public void setTipoMovimiento(TipoMovimiento tipoMovimiento) {
        this.tipoMovimiento = tipoMovimiento;
    }
    public long getNumero() {
        return this.numero;
    }
    
    public void setNumero(long numero) {
        this.numero = numero;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public int getIdTipoentrada() {
        return this.idTipoentrada;
    }
    
    public void setIdTipoentrada(int idTipoentrada) {
        this.idTipoentrada = idTipoentrada;
    }
    public Date getFechaDocref() {
        return this.fechaDocref;
    }
    
    public void setFechaDocref(Date fechaDocref) {
        this.fechaDocref = fechaDocref;
    }
    public String getNroDocref() {
        return this.nroDocref;
    }
    
    public void setNroDocref(String nroDocref) {
        this.nroDocref = nroDocref;
    }
    public int getIdAlmacendestino() {
        return this.idAlmacendestino;
    }
    
    public void setIdAlmacendestino(int idAlmacendestino) {
        this.idAlmacendestino = idAlmacendestino;
    }
    public int getIdUserReg() {
        return this.idUserReg;
    }
    
    public void setIdUserReg(int idUserReg) {
        this.idUserReg = idUserReg;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getIdComprobante() {
        return this.idComprobante;
    }
    
    public void setIdComprobante(Integer idComprobante) {
        this.idComprobante = idComprobante;
    }
    public Set<NotaEntradaDetalle> getNotaEntradaDetalles() {
        return this.notaEntradaDetalles;
    }
    
    public void setNotaEntradaDetalles(Set<NotaEntradaDetalle> notaEntradaDetalles) {
        this.notaEntradaDetalles = notaEntradaDetalles;
    }




}


