package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import org.springframework.stereotype.Component;

/**
 * NotaSalidaDetalle generated by hbm2java
 */
@Component
public class NotaSalidaDetalle implements java.io.Serializable {

    private long idnotasalidadetalle;
    private Producto producto;
    private String unidadmedida;
    private NotaSalida notasalida;
    private BigDecimal cantSolicitada;
    private BigDecimal cantAtendida;
    private BigDecimal cantPendiente;
    private BigDecimal cantSalida;
    private long idAlmacenProducto;
    private BigDecimal stock;
    private long idEquivalencia;

    public NotaSalidaDetalle() {
        this.idnotasalidadetalle = 0;
        this.producto = new Producto();
        this.notasalida = new NotaSalida();
    }

    public NotaSalidaDetalle(long idnotasalidadetalle, Producto producto, String unidadmedida, NotaSalida notasalida) {
        this.idnotasalidadetalle = idnotasalidadetalle;
        this.producto = producto;
        this.unidadmedida = unidadmedida;
        this.notasalida = notasalida;
    }

    public long getIdnotasalidadetalle() {
        return this.idnotasalidadetalle;
    }

    public void setIdnotasalidadetalle(long idnotasalidadetalle) {
        this.idnotasalidadetalle = idnotasalidadetalle;
    }

    public Producto getProducto() {
        return producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public String getUnidadmedida() {
        return unidadmedida;
    }

    public void setUnidadmedida(String unidadmedida) {
        this.unidadmedida = unidadmedida;
    }

    public NotaSalida getNotasalida() {
        return notasalida;
    }

    public void setNotasalida(NotaSalida notasalida) {
        this.notasalida = notasalida;
    }

    public long getIdAlmacenProducto() {
        return idAlmacenProducto;
    }

    public void setIdAlmacenProducto(long idAlmacenProducto) {
        this.idAlmacenProducto = idAlmacenProducto;
    }

    public BigDecimal getStock() {
        return stock;
    }

    public void setStock(BigDecimal stock) {
        this.stock = stock;
    }

    public BigDecimal getCantSolicitada() {
        return cantSolicitada;
    }

    public void setCantSolicitada(BigDecimal cantSolicitada) {
        this.cantSolicitada = cantSolicitada;
    }

    public BigDecimal getCantAtendida() {
        return cantAtendida;
    }

    public void setCantAtendida(BigDecimal cantAtendida) {
        this.cantAtendida = cantAtendida;
    }

    public BigDecimal getCantPendiente() {
        return cantPendiente;
    }

    public void setCantPendiente(BigDecimal cantPendiente) {
        this.cantPendiente = cantPendiente;
    }

    public BigDecimal getCantSalida() {
        return cantSalida;
    }

    public void setCantSalida(BigDecimal cantSalida) {
        this.cantSalida = cantSalida;
    }

    public long getIdEquivalencia() {
        return idEquivalencia;
    }

    public void setIdEquivalencia(long idEquivalencia) {
        this.idEquivalencia = idEquivalencia;
    }

}
