package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * OrdenCompraDetalle generated by hbm2java
 */
@Component
public class OrdenCompraDetalle  implements java.io.Serializable {


     private long idordencompradetalle;
     private OrdenCompra ordenCompra;
     private Producto producto;
     private int cantidad;
     private Integer idUnidadmedida;
     private String observacion;

    public OrdenCompraDetalle() {
    }

	
    public OrdenCompraDetalle(long idordencompradetalle, OrdenCompra ordenCompra, Producto producto, int cantidad) {
        this.idordencompradetalle = idordencompradetalle;
        this.ordenCompra = ordenCompra;
        this.producto = producto;
        this.cantidad = cantidad;
    }
    public OrdenCompraDetalle(long idordencompradetalle, OrdenCompra ordenCompra, Producto producto, int cantidad, Integer idUnidadmedida, String observacion) {
       this.idordencompradetalle = idordencompradetalle;
       this.ordenCompra = ordenCompra;
       this.producto = producto;
       this.cantidad = cantidad;
       this.idUnidadmedida = idUnidadmedida;
       this.observacion = observacion;
    }
   
    public long getIdordencompradetalle() {
        return this.idordencompradetalle;
    }
    
    public void setIdordencompradetalle(long idordencompradetalle) {
        this.idordencompradetalle = idordencompradetalle;
    }
    public OrdenCompra getOrdenCompra() {
        return this.ordenCompra;
    }
    
    public void setOrdenCompra(OrdenCompra ordenCompra) {
        this.ordenCompra = ordenCompra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Integer getIdUnidadmedida() {
        return this.idUnidadmedida;
    }
    
    public void setIdUnidadmedida(Integer idUnidadmedida) {
        this.idUnidadmedida = idUnidadmedida;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


