package org.siga.be;
// Generated 01/09/2018 12:46:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * OrdenCompraEstados generated by hbm2java
 */
@Component
public class OrdenCompraEstados  implements java.io.Serializable {


     private long idordencompraestados;
     private String descripcion;
     private String estado;
     private Set<OrdenCompraSeguimiento> ordenCompraSeguimientos = new HashSet<OrdenCompraSeguimiento>(0);

    public OrdenCompraEstados() {
    }

	
    public OrdenCompraEstados(long idordencompraestados, String descripcion, String estado) {
        this.idordencompraestados = idordencompraestados;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public OrdenCompraEstados(long idordencompraestados, String descripcion, String estado, Set<OrdenCompraSeguimiento> ordenCompraSeguimientos) {
       this.idordencompraestados = idordencompraestados;
       this.descripcion = descripcion;
       this.estado = estado;
       this.ordenCompraSeguimientos = ordenCompraSeguimientos;
    }
   
    public long getIdordencompraestados() {
        return this.idordencompraestados;
    }
    
    public void setIdordencompraestados(long idordencompraestados) {
        this.idordencompraestados = idordencompraestados;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<OrdenCompraSeguimiento> getOrdenCompraSeguimientos() {
        return this.ordenCompraSeguimientos;
    }
    
    public void setOrdenCompraSeguimientos(Set<OrdenCompraSeguimiento> ordenCompraSeguimientos) {
        this.ordenCompraSeguimientos = ordenCompraSeguimientos;
    }




}


