package org.siga.be;
// Generated 03/11/2017 11:21:41 AM by Hibernate Tools 4.3.1


import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * PedidoSeguimiento generated by hbm2java
 */
@Component
public class PedidoSeguimiento  implements java.io.Serializable {


     private long idpedidoseguimiento;
     private Pedido pedido;
     private PedidoEstados pedidoEstados;
     private Date fecha;
     private String hora;
     private String observacion;
     private int numero;
     private boolean estado;

    public PedidoSeguimiento() {
    }

	
    public PedidoSeguimiento(long idpedidoseguimiento, Pedido pedido, PedidoEstados pedidoEstados, Date fecha, String hora, int numero, boolean estado) {
        this.idpedidoseguimiento = idpedidoseguimiento;
        this.pedido = pedido;
        this.pedidoEstados = pedidoEstados;
        this.fecha = fecha;
        this.hora = hora;
        this.numero = numero;
        this.estado = estado;
    }
    public PedidoSeguimiento(long idpedidoseguimiento, Pedido pedido, PedidoEstados pedidoEstados, Date fecha, String hora, String observacion, int numero, boolean estado) {
       this.idpedidoseguimiento = idpedidoseguimiento;
       this.pedido = pedido;
       this.pedidoEstados = pedidoEstados;
       this.fecha = fecha;
       this.hora = hora;
       this.observacion = observacion;
       this.numero = numero;
       this.estado = estado;
    }
   
    public long getIdpedidoseguimiento() {
        return this.idpedidoseguimiento;
    }
    
    public void setIdpedidoseguimiento(long idpedidoseguimiento) {
        this.idpedidoseguimiento = idpedidoseguimiento;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public PedidoEstados getPedidoEstados() {
        return this.pedidoEstados;
    }
    
    public void setPedidoEstados(PedidoEstados pedidoEstados) {
        this.pedidoEstados = pedidoEstados;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


