package org.siga.be;
// Generated 03/11/2017 11:21:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * PedidoEstados generated by hbm2java
 */
@Component
public class PedidoEstados  implements java.io.Serializable {


     private long idpedidoestado;
     private String descripcion;
     private boolean estado;
     private Set<PedidoSeguimiento> pedidoSeguimientos = new HashSet<PedidoSeguimiento>(0);

    public PedidoEstados() {
    }

	
    public PedidoEstados(long idpedidoestado, String descripcion, boolean estado) {
        this.idpedidoestado = idpedidoestado;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public PedidoEstados(long idpedidoestado, String descripcion, boolean estado, Set<PedidoSeguimiento> pedidoSeguimientos) {
       this.idpedidoestado = idpedidoestado;
       this.descripcion = descripcion;
       this.estado = estado;
       this.pedidoSeguimientos = pedidoSeguimientos;
    }
   
    public long getIdpedidoestado() {
        return this.idpedidoestado;
    }
    
    public void setIdpedidoestado(long idpedidoestado) {
        this.idpedidoestado = idpedidoestado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set<PedidoSeguimiento> getPedidoSeguimientos() {
        return this.pedidoSeguimientos;
    }
    
    public void setPedidoSeguimientos(Set<PedidoSeguimiento> pedidoSeguimientos) {
        this.pedidoSeguimientos = pedidoSeguimientos;
    }




}


