package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import org.springframework.stereotype.Component;

/**
 *PedidoDetalle generated by hbm2java
 */
@Component
public class PedidoDetalle implements java.io.Serializable {

    public Producto getProducto() {
        return producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    private long idpedidodetalle;
    private Pedido pedido;
    private Producto producto;
    private BigDecimal cantidadSolicitada;
    private String unidadMedida;
    private BigDecimal cantidadAutorizada;
    private BigDecimal cantidadSurtida;
    private long idEquivalencia;

    public PedidoDetalle() {
        this.idpedidodetalle = 0;
        this.pedido = new Pedido();
        this.producto = new Producto();

    }

    public PedidoDetalle(long idpedidodetalle, Pedido pedido, BigDecimal cantidadSolicitada, BigDecimal cantidadAutorizada, BigDecimal cantidadSurtida) {
        this.idpedidodetalle = idpedidodetalle;
        this.pedido = pedido;
        this.cantidadSolicitada = cantidadSolicitada;
        this.cantidadAutorizada = cantidadAutorizada;
        this.cantidadSurtida = cantidadSurtida;
    }

    public PedidoDetalle(long idpedidodetalle, Pedido pedido, BigDecimal cantidadSolicitada, String unidadMedida, BigDecimal cantidadAutorizada, BigDecimal cantidadSurtida) {
        this.idpedidodetalle = idpedidodetalle;
        this.pedido = pedido;
        this.cantidadSolicitada = cantidadSolicitada;
        this.unidadMedida = unidadMedida;
        this.cantidadAutorizada = cantidadAutorizada;
        this.cantidadSurtida = cantidadSurtida;
    }

    public long getIdpedidodetalle() {
        return this.idpedidodetalle;
    }

    public void setIdpedidodetalle(long idpedidodetalle) {
        this.idpedidodetalle = idpedidodetalle;
    }

    public Pedido getPedido() {
        return this.pedido;
    }

    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

    public BigDecimal getCantidadSolicitada() {
        return this.cantidadSolicitada;
    }

    public void setCantidadSolicitada(BigDecimal cantidadSolicitada) {
        this.cantidadSolicitada = cantidadSolicitada;
    }

    public BigDecimal getCantidadAutorizada() {
        return this.cantidadAutorizada;
    }

    public void setCantidadAutorizada(BigDecimal cantidadAutorizada) {
        this.cantidadAutorizada = cantidadAutorizada;
    }

    public BigDecimal getCantidadSurtida() {
        return this.cantidadSurtida;
    }

    public void setCantidadSurtida(BigDecimal cantidadSurtida) {
        this.cantidadSurtida = cantidadSurtida;
    }

    public String getUnidadMedida() {
        return unidadMedida;
    }

    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }

    public long getIdEquivalencia() {
        return idEquivalencia;
    }

    public void setIdEquivalencia(long idEquivalencia) {
        this.idEquivalencia = idEquivalencia;
    }

}
