package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * PedidoDetalle generated by hbm2java
 */
@Component
public class PedidoDetalle  implements java.io.Serializable {


     private long idpedidodetalle;
     private Pedido pedido;
     private int idProducto;
     private int cantidadSolicitada;
     private Integer idUnidadMedida;
     private int cantidadAutorizada;
     private int cantidadSurtida;

    public PedidoDetalle() {
    }

	
    public PedidoDetalle(long idpedidodetalle, Pedido pedido, int idProducto, int cantidadSolicitada, int cantidadAutorizada, int cantidadSurtida) {
        this.idpedidodetalle = idpedidodetalle;
        this.pedido = pedido;
        this.idProducto = idProducto;
        this.cantidadSolicitada = cantidadSolicitada;
        this.cantidadAutorizada = cantidadAutorizada;
        this.cantidadSurtida = cantidadSurtida;
    }
    public PedidoDetalle(long idpedidodetalle, Pedido pedido, int idProducto, int cantidadSolicitada, Integer idUnidadMedida, int cantidadAutorizada, int cantidadSurtida) {
       this.idpedidodetalle = idpedidodetalle;
       this.pedido = pedido;
       this.idProducto = idProducto;
       this.cantidadSolicitada = cantidadSolicitada;
       this.idUnidadMedida = idUnidadMedida;
       this.cantidadAutorizada = cantidadAutorizada;
       this.cantidadSurtida = cantidadSurtida;
    }
   
    public long getIdpedidodetalle() {
        return this.idpedidodetalle;
    }
    
    public void setIdpedidodetalle(long idpedidodetalle) {
        this.idpedidodetalle = idpedidodetalle;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public int getCantidadSolicitada() {
        return this.cantidadSolicitada;
    }
    
    public void setCantidadSolicitada(int cantidadSolicitada) {
        this.cantidadSolicitada = cantidadSolicitada;
    }
    public Integer getIdUnidadMedida() {
        return this.idUnidadMedida;
    }
    
    public void setIdUnidadMedida(Integer idUnidadMedida) {
        this.idUnidadMedida = idUnidadMedida;
    }
    public int getCantidadAutorizada() {
        return this.cantidadAutorizada;
    }
    
    public void setCantidadAutorizada(int cantidadAutorizada) {
        this.cantidadAutorizada = cantidadAutorizada;
    }
    public int getCantidadSurtida() {
        return this.cantidadSurtida;
    }
    
    public void setCantidadSurtida(int cantidadSurtida) {
        this.cantidadSurtida = cantidadSurtida;
    }




}


