package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;

/**
 *PedidoDetalle generated by hbm2java
 */
@Component
public class PedidoDetalle implements java.io.Serializable {

    public Producto getProducto() {
        return producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    private long idpedidodetalle;
    private Pedido pedido;
    private Producto producto;
    private int cantidadSolicitada;
    private String unidadMedida;
    private int cantidadAutorizada;
    private int cantidadSurtida;

    public PedidoDetalle() {
        this.idpedidodetalle = 0;
        this.pedido = new Pedido();
        this.producto = new Producto();

    }

    public PedidoDetalle(long idpedidodetalle, Pedido pedido, int cantidadSolicitada, int cantidadAutorizada, int cantidadSurtida) {
        this.idpedidodetalle = idpedidodetalle;
        this.pedido = pedido;
        this.cantidadSolicitada = cantidadSolicitada;
        this.cantidadAutorizada = cantidadAutorizada;
        this.cantidadSurtida = cantidadSurtida;
    }

    public PedidoDetalle(long idpedidodetalle, Pedido pedido, int cantidadSolicitada, String unidadMedida, int cantidadAutorizada, int cantidadSurtida) {
        this.idpedidodetalle = idpedidodetalle;
        this.pedido = pedido;
        this.cantidadSolicitada = cantidadSolicitada;
        this.unidadMedida = unidadMedida;
        this.cantidadAutorizada = cantidadAutorizada;
        this.cantidadSurtida = cantidadSurtida;
    }

    public long getIdpedidodetalle() {
        return this.idpedidodetalle;
    }

    public void setIdpedidodetalle(long idpedidodetalle) {
        this.idpedidodetalle = idpedidodetalle;
    }

    public Pedido getPedido() {
        return this.pedido;
    }

    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

    public int getCantidadSolicitada() {
        return this.cantidadSolicitada;
    }

    public void setCantidadSolicitada(int cantidadSolicitada) {
        this.cantidadSolicitada = cantidadSolicitada;
    }

    public int getCantidadAutorizada() {
        return this.cantidadAutorizada;
    }

    public void setCantidadAutorizada(int cantidadAutorizada) {
        this.cantidadAutorizada = cantidadAutorizada;
    }

    public int getCantidadSurtida() {
        return this.cantidadSurtida;
    }

    public void setCantidadSurtida(int cantidadSurtida) {
        this.cantidadSurtida = cantidadSurtida;
    }

    public String getUnidadMedida() {
        return unidadMedida;
    }

    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }

}
