package org.siga.be;
// Generated 03/11/2017 11:21:41 AM by Hibernate Tools 4.3.1


import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * PedidoSeguimiento generated by hbm2java
 */
@Component
public class PedidoSeguimiento  implements java.io.Serializable {


     private long idpedidoseguimiento;
     private Pedido pedido;
     private Date fecha;
     private String hora;
     private String observacion;
     private int numero;
     private String estado;
     private long idUser;

    public PedidoSeguimiento() {
    }

	
   
   
    public long getIdpedidoseguimiento() {
        return this.idpedidoseguimiento;
    }
    
    public void setIdpedidoseguimiento(long idpedidoseguimiento) {
        this.idpedidoseguimiento = idpedidoseguimiento;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public long getIdUser() {
        return idUser;
    }

    public void setIdUser(long idUser) {
        this.idUser = idUser;
    }
    




}


