package org.siga.be;
// Generated 05/10/2018 10:07:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Permiso generated by hbm2java
 */
@Component
public class Permiso  implements java.io.Serializable {


     private long idpermiso;
     private int codigo;
     private String permiso;
     private String descripcion;
     private Integer estado;
     private Set<UsuarioPermiso> usuarioPermisos = new HashSet<UsuarioPermiso>(0);

    public Permiso() {
    }

	
    public Permiso(long idpermiso, int codigo, String permiso, String descripcion) {
        this.idpermiso = idpermiso;
        this.codigo = codigo;
        this.permiso = permiso;
        this.descripcion = descripcion;
    }
    public Permiso(long idpermiso, int codigo, String permiso, String descripcion, Integer estado, Set<UsuarioPermiso> usuarioPermisos) {
       this.idpermiso = idpermiso;
       this.codigo = codigo;
       this.permiso = permiso;
       this.descripcion = descripcion;
       this.estado = estado;
       this.usuarioPermisos = usuarioPermisos;
    }
   
    public long getIdpermiso() {
        return this.idpermiso;
    }
    
    public void setIdpermiso(long idpermiso) {
        this.idpermiso = idpermiso;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(String permiso) {
        this.permiso = permiso;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set<UsuarioPermiso> getUsuarioPermisos() {
        return this.usuarioPermisos;
    }
    
    public void setUsuarioPermisos(Set<UsuarioPermiso> usuarioPermisos) {
        this.usuarioPermisos = usuarioPermisos;
    }




}


