package org.siga.be;
// Generated 09/06/2017 11:14:22 PM by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * Producto generated by hbm2java
 */
@Component
public class Producto  implements java.io.Serializable {


     private int idproducto;
     private Categoria categoria;
     private Marca marca;
     private UnidadMedida unidadMedida;
     private String descripcion;
     private String codigo;
     private int stockMinimo;
     private int stockMaximo;

    public Producto() {
    }

    public Producto(int idproducto, Categoria categoria, Marca marca, UnidadMedida unidadMedida, String descripcion, String codigo, int stockMinimo, int stockMaximo) {
       this.idproducto = idproducto;
       this.categoria = categoria;
       this.marca = marca;
       this.unidadMedida = unidadMedida;
       this.descripcion = descripcion;
       this.codigo = codigo;
       this.stockMinimo = stockMinimo;
       this.stockMaximo = stockMaximo;
    }
   
    public int getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public UnidadMedida getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(UnidadMedida unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public int getStockMinimo() {
        return this.stockMinimo;
    }
    
    public void setStockMinimo(int stockMinimo) {
        this.stockMinimo = stockMinimo;
    }
    public int getStockMaximo() {
        return this.stockMaximo;
    }
    
    public void setStockMaximo(int stockMaximo) {
        this.stockMaximo = stockMaximo;
    }




}


