package org.siga.be;
// Generated 24/09/2018 11:04:28 AM by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * ProveedorFamilia generated by hbm2java
 */
@Component
public class ProveedorFamilia  implements java.io.Serializable {


     private long idproveedorfamilia;
     private Familia familia;
     private Proveedor proveedor;
     private String estado;

    public ProveedorFamilia() {
    }
    

    public ProveedorFamilia(long idproveedorfamilia, Familia familia, Proveedor proveedor, String estado) {
       this.idproveedorfamilia = idproveedorfamilia;
       this.familia = familia;
       this.proveedor = proveedor;
       this.estado = estado;
    }
   
    public long getIdproveedorfamilia() {
        return this.idproveedorfamilia;
    }
    
    public void setIdproveedorfamilia(long idproveedorfamilia) {
        this.idproveedorfamilia = idproveedorfamilia;
    }
    public Familia getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(Familia familia) {
        this.familia = familia;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


