package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * Rol generated by hbm2java
 */
@Component
public class Rol  implements java.io.Serializable {


     private long idrol;
     private String rol;
     private String descripcion;
     private Boolean estado;
     private Date fechaReg;

    public Rol() {
    }

	
    public Rol(long idrol) {
        this.idrol = idrol;
    }
    public Rol(long idrol, String rol, String descripcion, Boolean estado, Date fechaReg) {
       this.idrol = idrol;
       this.rol = rol;
       this.descripcion = descripcion;
       this.estado = estado;
       this.fechaReg = fechaReg;
    }
   
    public long getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(long idrol) {
        this.idrol = idrol;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }




}


