package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * TipoMovimiento generated by hbm2java
 */
@Component
public class TipoMovimiento  implements java.io.Serializable {


     private long idtipomovimiento;
     private String descripcion;
     private String estado;
     private Set<NotaEntrada> notaEntradas = new HashSet<NotaEntrada>(0);
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public TipoMovimiento() {
    }

	
    public TipoMovimiento(long idtipomov, String descripcion, String estado) {
        this.idtipomovimiento = idtipomov;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public TipoMovimiento(long idtipomov, String descripcion, String estado, Set<NotaEntrada> notaEntradas) {
       this.idtipomovimiento = idtipomov;
       this.descripcion = descripcion;
       this.estado = estado;
       this.notaEntradas = notaEntradas;
    }
   
    public long getIdtipomovimiento() {
        return this.idtipomovimiento;
    }
    
    public void setIdtipomovimiento(long idtipomovimiento) {
        this.idtipomovimiento = idtipomovimiento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<NotaEntrada> getNotaEntradas() {
        return this.notaEntradas;
    }
    
    public void setNotaEntradas(Set<NotaEntrada> notaEntradas) {
        this.notaEntradas = notaEntradas;
    }

    public Set<Pedido> getPedidos() {
        return pedidos;
    }

    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


