package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1

import org.springframework.stereotype.Component;




/**
 * TipoDocIdentidad generated by hbm2java
 */
@Component
public class TipoDocIdentidad  implements java.io.Serializable {


     private int idtipodocidentidad;
     private String documento;
     private Boolean estado;

    public TipoDocIdentidad() {
    }

	
    public TipoDocIdentidad(int idtipodocidentidad, String documento) {
        this.idtipodocidentidad = idtipodocidentidad;
        this.documento = documento;
    }
    public TipoDocIdentidad(int idtipodocidentidad, String documento, Boolean estado) {
       this.idtipodocidentidad = idtipodocidentidad;
       this.documento = documento;
       this.estado = estado;
    }
   
    public int getIdtipodocidentidad() {
        return this.idtipodocidentidad;
    }
    
    public void setIdtipodocidentidad(int idtipodocidentidad) {
        this.idtipodocidentidad = idtipodocidentidad;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


