package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * TipoMovimiento generated by hbm2java
 */
@Component
public class TipoMovimiento  implements java.io.Serializable {


     private int idtipomov;
     private String descripcion;
     private String estado;
     private Set<NotaEntrada> notaEntradas = new HashSet<NotaEntrada>(0);

    public TipoMovimiento() {
    }

	
    public TipoMovimiento(int idtipomov, String descripcion, String estado) {
        this.idtipomov = idtipomov;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public TipoMovimiento(int idtipomov, String descripcion, String estado, Set<NotaEntrada> notaEntradas) {
       this.idtipomov = idtipomov;
       this.descripcion = descripcion;
       this.estado = estado;
       this.notaEntradas = notaEntradas;
    }
   
    public int getIdtipomov() {
        return this.idtipomov;
    }
    
    public void setIdtipomov(int idtipomov) {
        this.idtipomov = idtipomov;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<NotaEntrada> getNotaEntradas() {
        return this.notaEntradas;
    }
    
    public void setNotaEntradas(Set<NotaEntrada> notaEntradas) {
        this.notaEntradas = notaEntradas;
    }




}


