package org.siga.be;
// Generated 21/07/2017 11:07:23 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * UnidadMedida generated by hbm2java
 */
@Component
public class UnidadMedida  implements java.io.Serializable {


     private long idunidadmedida;
     private String descripcion;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public UnidadMedida() {
        this.idunidadmedida = Long.MIN_VALUE;
    }

	
    public UnidadMedida(long idunidadmedida, String descripcion) {
        this.idunidadmedida = idunidadmedida;
        this.descripcion = descripcion;
    }
    public UnidadMedida(long idunidadmedida, String descripcion, Set<Producto> productos) {
       this.idunidadmedida = idunidadmedida;
       this.descripcion = descripcion;
       this.productos = productos;
    }
   
    public long getIdunidadmedida() {
        return this.idunidadmedida;
    }
    
    public void setIdunidadmedida(long idunidadmedida) {
        this.idunidadmedida = idunidadmedida;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


