package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * UnidadMedida generated by hbm2java
 */
@Component
public class UnidadMedida  implements java.io.Serializable {


     private long idunidadmedida;
     private String descripcion;
     private String estado;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public UnidadMedida() {
    }

	
    public UnidadMedida(long idunidadmedida, String descripcion, String estado) {
        this.idunidadmedida = idunidadmedida;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public UnidadMedida(long idunidadmedida, String descripcion, String estado, Set<Producto> productos) {
       this.idunidadmedida = idunidadmedida;
       this.descripcion = descripcion;
       this.estado = estado;
       this.productos = productos;
    }
   
    public long getIdunidadmedida() {
        return this.idunidadmedida;
    }
    
    public void setIdunidadmedida(long idunidadmedida) {
        this.idunidadmedida = idunidadmedida;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
}


