package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * UsuarioRol generated by hbm2java
 */
@Component
public class UsuarioRol  implements java.io.Serializable {


     private long idusuariorol;
     private Usuario usuario;
     private Rol rol;
     private Date fechaReg;
     private String descripcion;
     private Boolean estado;

    public UsuarioRol() {
        this.idusuariorol = 0;
        usuario = new Usuario();
        rol = new Rol();
    }

	
    public UsuarioRol(long idusuariorol, String descripcion) {
        this.idusuariorol = idusuariorol;
        this.descripcion = descripcion;
    }
    public UsuarioRol(long idusuariorol, Date fechaReg, String descripcion, Boolean estado) {
       this.idusuariorol = idusuariorol;
       this.fechaReg = fechaReg;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public long getIdusuariorol() {
        return this.idusuariorol;
    }
    
    public void setIdusuariorol(long idusuariorol) {
        this.idusuariorol = idusuariorol;
    }
   
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Rol getRol() {
        return rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


