package org.siga.be;
// Generated 07/08/2017 05:08:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * UsuarioRol generated by hbm2java
 */
@Component
public class UsuarioRol  implements java.io.Serializable {


     private long idusuariorol;
     private Integer idUsuario;
     private Integer idRol;
     private Date fechaReg;
     private String descripcion;
     private Boolean estado;

    public UsuarioRol() {
    }

	
    public UsuarioRol(long idusuariorol, String descripcion) {
        this.idusuariorol = idusuariorol;
        this.descripcion = descripcion;
    }
    public UsuarioRol(long idusuariorol, Integer idUsuario, Integer idRol, Date fechaReg, String descripcion, Boolean estado) {
       this.idusuariorol = idusuariorol;
       this.idUsuario = idUsuario;
       this.idRol = idRol;
       this.fechaReg = fechaReg;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public long getIdusuariorol() {
        return this.idusuariorol;
    }
    
    public void setIdusuariorol(long idusuariorol) {
        this.idusuariorol = idusuariorol;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


